name:                prof-scraper
version:             0.1.0.0
github:              "jeremysinger/prof-scraper"
license:             BSD3
author:              "Jeremy Singer"
maintainer:          "Jeremy.Singer@glasgow.ac.uk"
copyright:           "2020 Jeremy Singer"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Coursework for FP(H) - UoG web scraper
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeremysinger/prof-scraper#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- split
- mtl
- http-client
- gtk2hs-buildtools
- Chart-diagrams
- Chart
#- Chart-cairo
#- cairo

library:
  source-dirs: src

executables:
  prof-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prof-scraper
   
    

tests:
  prof-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prof-scraper
    - tasty
    - tasty-hunit
